### ISSUE TITLE
Tensorflow 2.16.1 compatibility

### ISSUE THREAD

**Issue by Stikus** [openvax/mhcflurry#234]
Hello, as you can see in pVACtools issue https://github.com/griffithlab/pVACtools/issues/1084 - mhcflurry and/or https://github.com/KarchinLab/mhcnuggets doesn't work with latest [2.16.1 version of tensorflow](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1).

```
Exception: An error occurred while calling MHCflurry:
Traceback (most recent call last):
  File "/usr/local/bin/mhcflurry-predict", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/mhcflurry/predict_command.py", line 204, in run
    predictor = Class1PresentationPredictor.load(models_dir)
  File "/usr/local/lib/python3.10/dist-packages/mhcflurry/class1_presentation_predictor.py", line 956, in load
    affinity_predictor = Class1AffinityPredictor.load(
  File "/usr/local/lib/python3.10/dist-packages/mhcflurry/class1_affinity_predictor.py", line 608, in load
    optimized = result.optimize()
  File "/usr/local/lib/python3.10/dist-packages/mhcflurry/class1_affinity_predictor.py", line 653, in optimize
    Class1NeuralNetwork.merge(
  File "/usr/local/lib/python3.10/dist-packages/mhcflurry/class1_neural_network.py", line 1148, in merge
    configure_tensorflow()
  File "/usr/local/lib/python3.10/dist-packages/mhcflurry/common.py", line 131, in configure_tensorflow
    tensorflow.compat.v1.keras.backend.set_session(session)
AttributeError: module 'keras._tf_keras.keras.backend' has no attribute 'set_session'. Did you mean: 'set_epsilon'?
```

Looks like some legacy code stopped working - maybe tensorflow version should be pinned until code is fixed?

**Comment by Stikus** [comment]
@timodonnell Thanks for fast answer. I'll double first - pVACtools still using mhcflurry 2.0.6 - https://github.com/griffithlab/pVACtools/blob/master/setup.py#L90, maybe this problem is already fixed in latest version.

**Comment by timodonnell** [comment]
Ah ok yes was just seeing that - I think it should be already fixed in the latest.

**Comment by jday1** [comment]
@timodonnell please see my PR for fix with passing tests: https://github.com/openvax/mhcflurry/pull/239
