### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

### ISSUE THREAD

**Issue by amomin-pact** [openvax/mhcflurry#150]
Hi ,
    When I try to run the ```mhcflurry-predict --alleles HLA-A*02:04 --peptides SIINFEKL``` , I get the following error. AttributeError: module 'tensorflow' has no attribute 'ConfigProto'. 

    Is mhcFlurry dependent on a specific tensorflow version.

 Thanks

**Comment by timodonnell** [comment]
Which version of tensorflow are you using?

**Comment by amomin-pact** [comment]
tensorflow                2.0.0
keras                     2.3.1

**Comment by timodonnell** [comment]
Thanks for reporting this - we may not be compatible with tensorflow 2.0. Can you try a 1.x version (I think the latest and 1.15) and let me know if that fixes this for you?

**Comment by amomin-pact** [comment]
Thanks the package works with TF1.14

**Comment by timodonnell** [comment]
Reopening since we should either support tensorflow 2 or explicitly indicate that we depend on tensorflow < 2
